### ISSUE TITLE
AttributeError: 'RetinaNet' object has no attribute 'module'

### ISSUE THREAD

**Issue by Phoebe-star** [wsnedy/pytorch-retinanet#1]
Traceback (most recent call last):
  File "train.py", line 155, in <module>
    train(epoch)
  File "train.py", line 97, in train
    net.module.freeze_bn()
  File "/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'RetinaNet' object has no attribute 'module'

**Comment by wsnedy** [comment]
Hi, sorry for the late reply. The model has the `module` attribute when it is wrapped by `DataParallel`. Maybe you only use a single GPU, and try to add `DataParallel` instead of using`net.cuda()` directly.

**Comment by EvanAlbee** [comment]
@wsnedy  
Could you explain why we exclude the background like below in loss.py?
`t = t[:, 1:]  # exclude background`
Thanks!
